# This Docker Compose file is used to run the project's published image
#
# Usage: docker compose up [-d] [--env-file=path/to/file]
#
# See comment in docker-compose.dev.yml if you want to run for development.

version: '3'

services:
  database:
    container_name: micro-pkc-database
    image: xlp0/mariadb
    restart: always
    networks:
      - common
    environment:
      # Multiple dbs provisioned in provision/mariadb/01-databases.sql
      # MYSQL_DATABASE: my_wiki 
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER_FILE: /run/secrets/db_admin_user
      MYSQL_PASSWORD_FILE: /run/secrets/db_admin_pass
    secrets:
      - db_admin_user
      - db_admin_pass
    volumes:
      - ./mountPoint/mariadb:/var/lib/mysql
      - ./provision/mariadb:/docker-entrypoint-initdb.d
      - ./mountPoint/backup:/backup
      - ./mountPoint/MediaWiki_Backup:/MediaWiki_Backup

  mediawiki:
    container_name: micro-pkc-mediawiki
    image: fantasticofox/pkc:latest
    restart: always
    networks:
      - common
      # Do not delete the comment below! It is used for adding an external
      # network for deploying an internet-accessible PKC .
      #WEBPUBLICPLACEHOLDER
    ports:
      - ${MEDIAWIKI_PORT}:80
    entrypoint: '/var/www/html/aqua/entrypoint_mediawiki.sh'
    environment:
      - VIRTUAL_HOST=${MEDIAWIKI_HOST}
      - LETSENCRYPT_HOST=${MEDIAWIKI_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - EAUTH_PORT=${EAUTH_PORT}
    volumes:
      - ./mountPoint/images:/var/www/html/images
      - ./mountPoint/extensions/DataAccounting:/var/www/html/extensions/DataAccounting
      - ./mountPoint/backup:/backup
      - ./aqua:/var/www/html/aqua
      - ./mountPoint/MediaWiki_Backup:/MediaWiki_Backup
    depends_on:
      - database
      - eauth

  eauth:
    container_name: micro-pkc-eauth
    image: pelith/node-eauth-server:latest
    restart: always
    networks:
      - common
      # Do not delete the comment below! It is used for adding an external
      # network for deploying an internet-accessible PKC .
      #WEBPUBLICPLACEHOLDER
    env_file:
      - .env
    ports:
      - ${EAUTH_PORT}:${EAUTH_PORT}
    environment:
      - VIRTUAL_HOST=${EAUTH_HOST}
      - LETSENCRYPT_HOST=${EAUTH_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - VIRTUAL_PORT=${EAUTH_PORT}
    depends_on:
      - database

networks:
  # We specify the internal network as common, so that the services in this
  # docker-compose.yml can be configured to interact with the services in the
  # other, separate docker-compose.yml using external networks.
  common:

secrets:
  db_admin_user:
    file: ./db_admin_user.asc
  db_admin_pass:
    file: ./db_admin_pass.asc
